# IO Type
IO_SENSOR_DATA = 5
IO_DEVICE_DATA = 6
IO_APPRAW_DATA = 10

# Device Data
DEVICE_DATA_GENERAL = 1
DEVICE_DATA_LPWANAPPCONFIG = 2

SENSOR_RANGE_ACC_G = 4      # unit: g
SENSOR_RANGE_ACC_MS = 5     # unit: m/s^2

FFT_X_IDX = 1
FFT_Y_IDX = 2
FFT_Z_IDX = 4

#  Sensor Data Data Index and Length
SENSOR_DATA_IDX_LOGIDX_UTC = 11
SENSOR_DATA_IDX_LOGIDX_UTC_LEN = 9

SENSOR_DATA_IDX_LOGIDX = 9
SENSOR_DATA_IDX_LOGIDX_LEN = 5

# Device Data Data Index and Length
DEVICE_DATA_GENERAL_IDX_U = 1
DEVICE_DATA_GENERAL_IDX_U_LEN = 5
DEVICE_DATA_GENERAL_IDX_I = 2
DEVICE_DATA_GENERAL_IDX_I_LEN = 27
DEVICE_DATA_LPWANAPPCONFIG_IDX_I = 1  # Uplink Interval
DEVICE_DATA_LPWANAPPCONFIG_IDX_I_LEN = 5
DEVICE_DATA_LPWANAPPCONFIG_IDX_S = 2  # Uplink Schedule
DEVICE_DATA_LPWANAPPCONFIG_IDX_S_LEN = 11

PARA_LOGIDX_SIZE = 4
PARA_TIME_SIZE = 4

# FFT Downlink Type
FFT_TYPE_L = 0
FFT_TYPE_LT = 1

# Time Sync Downlink Type
TIMESYNC_TYPE_U = 0
TIMESYNC_TYPE_I = 1